name: Test

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout codes
        uses: actions/checkout@v2
      - name: post run - upload junit test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-junit-reports-foo-bar
          path: "**/*.xml"
          retention-days: 7
      - name: build inline test report 
        # only triggered by another workflow
        uses: dorny/test-reporter@v1
        with:
          name: "Tests Report $1"
          path: "**/*.xml"
          reporter: java-junit
    